# 文件编辑工具包配置
name: file_edit
mode: builtin
activated_tools: null  # null表示激活所有工具
config:
  workspace_root: "/tmp/naga_file_edit"  # 工作目录
  backup_enabled: true  # 启用备份
  default_encoding: "utf-8"  # 默认编码
